simulation_orchestrator:
  ros__parameters:
    num_agents: 10
    heartbeat_interval_ms: 500
    nodes_name_prefix: "agent_"
    agent_type: "ring"                    # Options: "bully", "hybrid_ring", ring"

chaos_monkey:
  ros__parameters:
    discovery_time_s: 10
    kill_interval_s: 5
    target_nodes_prefix: "agent_"
